## COMP263 - Deep Learning Lab 1

#### Forward and Backward Propogation

In [2]:
import numpy as np

Generating data

In [3]:
# X = (hours studying, hours sleeping), y = score on test
x_all = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float) # input data
y = np.array(([92], [86], [89]), dtype=float) # output

Scaling data

In [4]:
#Scaling training data so that all datapoints are between 0 and 1
x_all = x_all/np.max(x_all, axis=0) # scaling input data

In [5]:
#Scaling the y data - max test score is 100
y = y/100

Splitting data into training and testing

In [8]:
X = np.split(x_all, [3])[0] # training data

In [9]:
x_predicted = np.split(x_all, [3])[1] # testing data

Forward propogation to predict a score for input data

In [10]:
class neural_network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #Initializing weights randomly

        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
    
    #sigmoid activation function
    def sigmoid(self, s):
        return 1/(1+np.exp(-s))


    #forward propagation through our network
    def forward(self, X):
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 2x3 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o

nn = neural_network()

#defining our output
o = nn.forward(X)

print("Predicted Output: \n" + str(o))
print("Actual Output: \n" + str(y))

Predicted Output: 
[[0.565499  ]
 [0.56959097]
 [0.60329515]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]


Backpropogation

In [11]:
class neural_network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #Initializing weights randomly

        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
    
    #sigmoid activation function
    def sigmoid(self, s):
        return 1/(1+np.exp(-s))


    #forward propagation through our network
    def forward(self, X):
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 2x3 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o


    def sigmoidPrime(self, s): #derivative of sigmoid
        return s * (1 - s)

     # backward propagate through the network
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error
        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(x_predicted))
        print("Output: \n" + str(self.forward(x_predicted)))

nn = neural_network()
for i in range(1000): # trains the nn 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(nn.forward(X)))
    print("Loss: \n" + str(np.mean(np.square(y - nn.forward(X))))) # mean squared error
    print("\n")
    nn.train(X, y)

nn.saveWeights()
nn.predict()

       

    

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.28611896]
 [0.2943973 ]
 [0.3127806 ]]
Loss: 
0.3516312752099499


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.35401547]
 [0.35982964]
 [0.37328342]]
Loss: 
0.27916830114977315


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.42413031]
 [0.42763857]
 [0.43430653]]
Loss: 
0.21349323088804187


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.49031596]
 [0.49183411]
 [0.49123232]]
Loss: 
0.15973005310837898


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.54854743]
 [0.54835482]
 [0.54122824]]
Loss: 
0.11891382317038919


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actua